export const MARKET_OPS: readonly string[] = [
  "respond_transfer_request",
  "revoke_mandate",
  "set_transfer_list",
  "delegate_negotiation",
  "release_player",
  "exercise_buyback",
  "recall_loan",
  "adjust_transfer_budget",
  "request_board",
  "set_ticket_price",
  "release_staff",
  "hire_staff",
  "accept_manager_offer",
  "counter_manager_offer",
  "apply_manager_job",
];
