/** 에이전트 카탈로그와 브라우저가 공유하는 호출 표시 이름. */
export const CALL_LABELS = {
  start_match: "경기 시작",
  accept_manager_offer: "감독직 수락",
  counter_manager_offer: "감독직 흥정",
  apply_manager_job: "감독직 지원",
  tactic_orders: "전술 지시",
  training_orders: "훈련 지시",
  market_orders: "이적·재정 지시",
  // 협상 방 — 여는 스킬 하나와 방 안의 도구 셋 (transfer.md §12-2)
  start_negotiation: "협상 시작",
  negotiation_orders: "협상 지시",
  counterparty_reply: "상대의 답",
  leave_negotiation: "물러나기",
  set_lineup: "라인업",
  set_squad_level: "1·2군 이동",
  set_captain: "완장 지정",
  set_squad_number: "등번호",
  set_development_focus: "집중 육성",
  set_mentor: "멘토링",
  set_reserve_training: "2군 훈련 방침",
  sign_youth: "유스 첫 계약",
  set_tactics: "팀 전술 변경",
  set_player_tactic: "선수 전술",
  set_set_piece_takers: "세트피스 키커",
  set_set_piece_routine: "세트피스 인원",
  set_training: "훈련 지정",
  set_shootout_order: "승부차기 순서",
  team_talk: "대화",
  review_board: "보드 평가",
  respond_to_media: "기자회견 대응",
  respond_to_approach: "찾아온 사람 응대",
  substitute: "선수 교체",
  record_incident: "사건 기록",
  apply_finance_event: "재정 이벤트",
  adjust_transfer_budget: "이적 예산 조정",
  request_board: "보드에 요청",
  set_ticket_price: "티켓 가격",
  hire_staff: "스태프 고용",
  release_staff: "스태프 계약 해지",
  resign: "사임",
  search_players: "선수 검색",
  get_squad: "스쿼드·라인업 조회",
  get_team: "팀 조회",
  get_league: "리그·일정 조회",
  get_career: "커리어 조회",
  get_history: "역대 기록 조회",
  get_finance: "재정 조회",
  get_match_report: "경기 리포트",
  get_opponent_report: "상대 분석",
  scout_player: "스카우트 파견",
  scout_mission: "스카우트 임무",
  deal_odds: "딜 성공 확률",
  list_negotiations: "협상 목록",
  send_offer: "오퍼",
  respond_offer: "오퍼 판정",
  accept_deal: "계약 확정",
  set_transfer_list: "이적 리스트",
  respond_transfer_request: "이적 요청 응답",
  withdraw_offer: "협상 철회",
  release_player: "계약 해지",
  recall_loan: "임대 복귀",
  exercise_buyback: "되사기 행사",
  open_renewal: "재계약 제안",
  open_release: "해지 제안",
  // 조건서 — 감독이 조건을 걸거나 상대의 요구에 답한다 (transfer.md §12-3)
  offer_terms: "조건 제시",
  answer_term: "요구 응답",
  propose_personal: "개인 조건 제안",
  // 위임 — 단장에게 맡기고 도로 가져온다 (transfer.md §12-4)
  delegate_negotiation: "협상 위임",
  revoke_mandate: "위임 취소",
  // 도구가 아니라 코어가 남기는 기록 — 카탈로그에 없지만 칩으로 선다
  finalize_match: "경기 종료",
} as const;
